site_name: Minnt Framework
site_url: https://minnt.org/
repo_url: https://github.com/ufal/minnt
docs_dir: src
watch: [../minnt, ../examples]
nav:
- index.md
- examples.md
- trainable_module.md
- transformed_dataset.md
- type_aliases.md
- utilities.md
- vocabulary.md
- Callbacks:
  - callback.md
  - callbacks/keep_best_weights.md
  - callbacks/save_best_weights.md
  - callbacks/save_weights.md
- Loggers:
  - logger.md
  - loggers/base_logger.md
  - loggers/filesystem_logger.md
  - loggers/multi_logger.md
  - loggers/tensorboard_logger.md
  - loggers/wandb_logger.md
- Losses:
  - loss.md
  - losses/binary_cross_entropy.md
  - losses/categorical_cross_entropy.md
  - losses/mean_squared_error.md
- Metrics:
  - metric.md
  - metrics/binary_accuracy.md
  - metrics/binary_cross_entropy.md
  - metrics/categorical_accuracy.md
  - metrics/categorical_cross_entropy.md
  - metrics/exact_match.md
  - metrics/mean.md
  - metrics/mean_squared_error.md
- Optimizers:
  - optimizers/adafactor.md
  - optimizers/lazy_adam.md
  - optimizers/multi_optimizer.md
- Schedulers:
  - schedulers/cosine_decay.md
  - schedulers/generic_decay.md
  - schedulers/linear_decay.md
  - schedulers/no_decay.md
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths:
        - ../
        inventories:
        - https://docs.python.org/3/objects.inv
        - https://pytorch.org/docs/stable/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        options:
          docstring_section_style: list
          members_order: source
          group_by_category: false
          show_root_heading: true
          show_symbol_type_toc: true
          show_symbol_type_heading: true
          show_signature_annotations: true
          separate_signature: true
          signature_crossrefs: true
          line_length: 80
          extensions:
          - griffe_inherited_docstrings
- markdown-exec
- privacy: {assets_exclude: [unpkg.com/mermaid*]}
markdown_extensions:
  attr_list:
  pymdownx.arithmatex:
    generic: true
    inline_syntax: [dollar]
    block_syntax: [dollar]
  pymdownx.highlight:
  pymdownx.inlinehilite:
  pymdownx.snippets:
    base_path: [., ..]
    check_paths: true
  pymdownx.superfences:
  pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
theme:
  name: material
  logo: images/leaf-green.svg
  favicon: images/leaf-green.svg
  custom_dir: template
  features:
  - content.code.copy
  - navigation.top
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: deep orange
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
extra:
  generator: false
extra_css:
- stylesheets/extra.css
- https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css
extra_javascript:
- javascripts/katex.js
- https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js
